[2024-04-22T15:00:03.658+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T03:00:00+00:00 [queued]>
[2024-04-22T15:00:03.662+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T03:00:00+00:00 [queued]>
[2024-04-22T15:00:03.663+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-22T15:00:03.674+0900] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): prepare_data> on 2024-04-22 03:00:00+00:00
[2024-04-22T15:00:03.678+0900] {standard_task_runner.py:57} INFO - Started process 13082 to run task
[2024-04-22T15:00:03.684+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'usd_krw_prediction_v1', 'prepare_data', 'scheduled__2024-04-22T03:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/m6/3b3l583d1z9f5sjd_k30vc7h0000gp/T/tmp99hmy50h']
[2024-04-22T15:00:03.687+0900] {standard_task_runner.py:85} INFO - Job 19: Subtask prepare_data
[2024-04-22T15:00:03.844+0900] {task_command.py:410} INFO - Running <TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T03:00:00+00:00 [running]> on host lm-045768-00.local
[2024-04-22T15:00:03.893+0900] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='usd_krw_prediction_v1' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T03:00:00+00:00'
[2024-04-22T15:00:03.895+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/m6/3b3l583d1z9f5sjd_k30vc7h0000gp/T
[2024-04-22T15:00:03.896+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/Users/boycho/Project/exchange/bat/prepare_data.sh ']
[2024-04-22T15:00:03.902+0900] {subprocess.py:86} INFO - Output:
[2024-04-22T15:00:03.948+0900] {subprocess.py:93} INFO - python /Users/boycho/Project/exchange/bat/../exchange/prepare_data.py --dt 2024-04-22 --naver_keyword_csv /Users/boycho/Project/exchange/bat/../data/naver_keyword_data.csv --kr_oil_hist_csv /Users/boycho/Project/exchange/bat/../data/kr_oil_historical_data.csv --us_10y_hist_csv /Users/boycho/Project/exchange/bat/../data/us_10year_bond_yield_historical_data.csv --us_1y_hist_csv /Users/boycho/Project/exchange/bat/../data/us_1year_bond_yield_historical_data.csv --us_bb_hist_csv /Users/boycho/Project/exchange/bat/../data/us_bb_high_yield_historical_data.csv --us_bb_tmp_csv /Users/boycho/Project/exchange/bat/../data/us_bb_tmp_data.csv --log_dir /Users/boycho/Project/exchange/bat/../log
[2024-04-22T15:00:06.062+0900] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-22T15:00:06.063+0900] {subprocess.py:93} INFO -   File "/Users/boycho/Project/exchange/bat/../exchange/prepare_data.py", line 22, in <module>
[2024-04-22T15:00:06.064+0900] {subprocess.py:93} INFO -     c_crawling = C_CRAWLING(logger)
[2024-04-22T15:00:06.065+0900] {subprocess.py:93} INFO -   File "/Users/boycho/Project/exchange/exchange/common/crawling.py", line 21, in __init__
[2024-04-22T15:00:06.065+0900] {subprocess.py:93} INFO -     self.slackalert = SlackAlert(self.logger)
[2024-04-22T15:00:06.066+0900] {subprocess.py:93} INFO - NameError: name 'SlackAlert' is not defined
[2024-04-22T15:00:06.185+0900] {subprocess.py:93} INFO - [ERROR] 1. prepare data for crawling
[2024-04-22T15:00:06.187+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-22T15:00:06.196+0900] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/boycho/anaconda3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-22T15:00:06.202+0900] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=usd_krw_prediction_v1, task_id=prepare_data, execution_date=20240422T030000, start_date=20240422T060003, end_date=20240422T060006
[2024-04-22T15:00:06.214+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task prepare_data (Bash command failed. The command returned a non-zero exit code 1.; 13082)
[2024-04-22T15:00:06.237+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-04-22T15:00:06.322+0900] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
