[2024-04-22T12:11:09.291+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-22T12:11:09.297+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-22T12:11:09.297+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-22T12:11:09.307+0900] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): prepare_data> on 2024-04-22 00:00:00+00:00
[2024-04-22T12:11:09.311+0900] {standard_task_runner.py:57} INFO - Started process 94690 to run task
[2024-04-22T12:11:09.317+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'usd_krw_prediction_v1', 'prepare_data', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/m6/3b3l583d1z9f5sjd_k30vc7h0000gp/T/tmp_zyjzms9']
[2024-04-22T12:11:09.320+0900] {standard_task_runner.py:85} INFO - Job 5: Subtask prepare_data
[2024-04-22T12:11:09.487+0900] {task_command.py:410} INFO - Running <TaskInstance: usd_krw_prediction_v1.prepare_data scheduled__2024-04-22T00:00:00+00:00 [running]> on host lm-045768-00.local
[2024-04-22T12:11:09.547+0900] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='usd_krw_prediction_v1' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-22T12:11:09.549+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/m6/3b3l583d1z9f5sjd_k30vc7h0000gp/T
[2024-04-22T12:11:09.550+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/Users/boycho/Project/exchange/bat/prepare_data.sh ']
[2024-04-22T12:11:09.556+0900] {subprocess.py:86} INFO - Output:
[2024-04-22T12:11:09.562+0900] {subprocess.py:93} INFO - /bin/bash: /Users/boycho/Project/exchange/bat/prepare_data.sh: Permission denied
[2024-04-22T12:11:09.563+0900] {subprocess.py:97} INFO - Command exited with return code 126
[2024-04-22T12:11:09.577+0900] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/boycho/anaconda3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2024-04-22T12:11:09.582+0900] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=usd_krw_prediction_v1, task_id=prepare_data, execution_date=20240422T000000, start_date=20240422T031109, end_date=20240422T031109
[2024-04-22T12:11:09.590+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task prepare_data (Bash command failed. The command returned a non-zero exit code 126.; 94690)
[2024-04-22T12:11:09.624+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-04-22T12:11:09.708+0900] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
